CREATE DATABASE IF NOT EXISTS CarRentDB;

USE CarRentDB;

CREATE TABLE CarRentDB.Cars (
	Id INT NOT NULL AUTO_INCREMENT,
	Marke VARCHAR(45) NULL,
	Seriennummer VARCHAR(45) NULL,
	Typ VARCHAR(45) NULL,
	Farbe VARCHAR(45) NULL,
	Vermietet BOOL DEFAULT FALSE,
    PRIMARY KEY (Id))
;

CREATE TABLE CarRentDB.Adress(
	AdressId INT NOT NULL AUTO_INCREMENT,
    Strasse VARCHAR(45) NULL,
    Strassennummer VARCHAR(45) NULL,
    PLZ VARCHAR(45) NULL,
    Ort VARCHAR(45) NULL,
    PRIMARY KEY (AdressId))
;

CREATE TABLE CarRentDB.Customer(
	CustomerId INT NOT NULL AUTO_INCREMENT,
    Vorname VARCHAR(45) NULL,
    Nachname VARCHAR(45) NULL,
    Telefonnummer VARCHAR(45) NULL,
    FK_Adressnummer INT NULL,
    PRIMARY KEY (CustomerId),
    FOREIGN KEY (FK_Adressnummer) REFERENCES CarRentDB.Adress(AdressID))
;